on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  beta:
    environment: beta
    runs-on: ubuntu-latest
    name: Beta
    steps:
      - name: Hello world action step
        id: hello
        uses: oysteinvesth/gh-actions-demo@v1.18
        with:
          who-to-greet: 'Mona the Octocat'
          google_credentials: ${{ secrets.GOOGLE_SA_JSON_KEY }}
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
  prod:
    environment: prod
    needs: beta
    runs-on: ubuntu-latest
    name: Production
    steps:
      - name: Production
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        
      - name: Hello world action step
        id: hello
        uses: oysteinvesth/gh-actions-demo@v1.18
        with:
          who-to-greet: 'Mona the Octocat'
          google_credentials: ${{ secrets.GOOGLE_SA_JSON_KEY }}