on: [push, pull_request, release, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: oysteinvesth/gh-actions-demo@v1.18
        with:
          who-to-greet: 'Mona the Octocat'
          google_credentials: ${{ secrets.GOOGLE_SA_JSON_KEY }}
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"